services:
  tado-data-collecton:
    build: .
    environment:
      - TADO_USERNAME=$TADO_USERNAME
      - TADO_PASSWORD=$TADO_PASSWORD
      - TADO_CLIENT_SECRET=$TADO_CLIENT_SECRET
      - INFLUX_URL=$INFLUX_URL
      - INFLUX_DB=$INFLUX_DB
